# Generated by Django 3.1 on 2020-08-20 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Car's name", max_length=100)),
                ('model', models.CharField(help_text="Car's model", max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Fabrication Year')),
                ('total_gas_capacity', models.FloatField(help_text='Total Gas Capacity in liters')),
                ('current_gas_capacity', models.FloatField(default=0, help_text='Current Gas Capacity in %')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degradation', models.FloatField(default=0, help_text='Degradation Status in %')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyres', to='cars.car')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
